<?php
$pages = [
 'inicio'=>['label'=>'Página inicial','enabled'=>true,'eyebrow'=>'Streetwear autoral · BRYXA','title'=>'ARTE PARA\nVESTIR.','description'=>'Peças que expressam quem você é. Conheça o universo BRYXA.','banner'=>'assets/hero-home-cs2-v4.webp','button'=>'Explorar coleção','target'=>'colecao'],
 'roupas'=>['label'=>'Roupas','enabled'=>true,'eyebrow'=>'Arte. Atitude. Liberdade.','title'=>'SUA ESSÊNCIA.\nSEU ESTILO.','description'=>'Do digital para a vida real. Criamos roupas para quem escolhe o próprio caminho.','banner'=>'assets/hero-cs2-v3.webp','button'=>'Ver peças','target'=>'colecao'],
 'cs2'=>['label'=>'CS2','enabled'=>true,'eyebrow'=>'Dentro e fora do jogo','title'=>'SEU JOGO.\nSEU ESTILO.','description'=>'Peças inspiradas no universo Counter-Strike 2.','banner'=>'assets/hero-cs2-v3.webp','button'=>'Explorar CS2','target'=>'produtos','parent'=>'roupas'],
 'rust'=>['label'=>'Rust','enabled'=>true,'eyebrow'=>'Sobreviva. Crie. Expresse.','title'=>'FORA DO\nCOMUM.','description'=>'O universo da sobrevivência encontra o seu estilo. Conheça a coleção Rust.','banner'=>'assets/hero-rust-v3.webp','button'=>'Explorar Rust','target'=>'produtos','parent'=>'roupas'],
 '3d'=>['label'=>'Peças e objetos 3D','enabled'=>true,'eyebrow'=>'Arsenal · Coleção 3D','title'=>'ARTE EM\nTRÊS DIMENSÕES.','description'=>'Explore os acessórios da coleção 3D.','banner'=>'assets/hero-3d-v6.webp','button'=>'Ver coleção 3D','target'=>'produtos','parent'=>'arsenal'],
 'personalizado'=>['label'=>'Personalize','enabled'=>true,'eyebrow'=>'Sua ideia. Nossa arte.','title'=>'FEITO DO\nSEU JEITO.','description'=>'Escolha a peça e conte a sua ideia. Uma nova forma de vestir sua identidade.','banner'=>'assets/hero-personalizado-v5.webp','button'=>'Personalizar','target'=>'personalizar'],
 'arsenal'=>['label'=>'Arsenal','enabled'=>true,'eyebrow'=>'O estilo está nos detalhes','title'=>'LEVE SUA\nESSÊNCIA.','description'=>'Acessórios para acompanhar você em qualquer lugar.','banner'=>'assets/hero-arsenal-v5.webp','button'=>'Ver acessórios','target'=>'produtos']
];

$pages['canecas']=json_decode('{"label": "Canecas", "enabled": true, "eyebrow": "BRYXA · Canecas", "title": "CANECAS", "description": "Canecas que levam a identidade BRYXA para sua rotina.", "banner": "assets/hero-canecas-v6.webp", "button": "Ver peças", "target": "produtos", "parent": "arsenal"}',true);
$pages['bottons-e-bags']=json_decode('{"label": "Bottons e Bags", "enabled": true, "eyebrow": "BRYXA · Bottons e Bags", "title": "BOTTONS E BAGS", "description": "Bottons e bags para expressar seu estilo nos detalhes.", "banner": "assets/hero-bottons-e-bags-v6.webp", "button": "Ver peças", "target": "produtos", "parent": "arsenal"}',true);
$pages['chaveiros']=json_decode('{"label": "Chaveiros", "enabled": true, "eyebrow": "BRYXA · Chaveiros", "title": "CHAVEIROS", "description": "Chaveiros para levar sua identidade com você.", "banner": "assets/hero-chaveiros-v6.webp", "button": "Ver peças", "target": "produtos", "parent": "arsenal"}',true);
$pages['drop-especial']=json_decode('{"label": "Drops Especiais", "enabled": true, "eyebrow": "BRYXA · Drops Especiais", "title": "DROPS ESPECIAIS", "description": "Confira as peças selecionadas para o drop especial da BRYXA.", "banner": "assets/hero-drop-especial-v5.webp", "button": "Ver peças", "target": "produtos", "parent": ""}',true);
$pageOrder=['inicio','roupas','cs2','rust','arsenal','canecas','bottons-e-bags','3d','chaveiros','personalizado','drop-especial'];$pages=array_replace(array_fill_keys($pageOrder,[]),$pages);
$products=[];
$names=['Moletom Essential','Camiseta Aura','Moletom Shadow Skull CS2','Camiseta Specter CS2','Moletom Outpost','Camiseta Raid','Bermuda Flame','Boné Essential','Shoulder Bag','Mousepad Inferno','Caneca BRYXA','Moletom Serpent CS2'];
$types=['Moletom','Camiseta','Moletom','Camiseta','Moletom','Camiseta','Bermuda','Boné','Bolsa','Mousepad','Caneca','Moletom'];
$collections=['roupas','roupas','cs2','cs2','rust','rust','roupas','arsenal','bottons-e-bags','arsenal','canecas','cs2'];
foreach($names as $i=>$name){$type=$types[$i];$sizes=in_array($type,['Moletom','Camiseta','Bermuda'])?['P','M','G','GG','XG']:['Único'];$products[]=['id'=>'p'.($i+1),'name'=>$name,'category'=>$type,'collection'=>$collections[$i],'price'=>$type==='Moletom'?289.9:($type==='Camiseta'||$type==='Bermuda'?169.9:89.9),'description'=>'Peça ilustrativa da coleção BRYXA. Fotos, medidas e composição serão atualizadas pela loja antes do lançamento.','image'=>'assets/product-'.($i+1).'.webp','sizes'=>$sizes,'stock'=>array_fill_keys($sizes,10),'active'=>true,'featured'=>$i<4,'weight'=>$type==='Moletom'?0.7:0.3,'width'=>25,'height'=>6,'length'=>30];}
return ['products'=>$products,'settings'=>['brand'=>'BRYXA','domain'=>'bryxa.art','announcement'=>'','home_products_title'=>'Drops selecionados.','collections_title'=>'Explore seu universo.','newsletter_title'=>'Faça parte da BRYXA.','newsletter_description'=>'Novos drops e novidades, no seu e-mail.','footer_description'=>'Do digital para a vida real.','about'=>'BRYXA é arte em movimento. Uma marca para quem escolhe o próprio caminho.\n\nNossa identidade nasce da conexão entre o universo digital, a criatividade e a liberdade de expressão.','contact_email'=>'','whatsapp'=>'','instagram'=>'','discord'=>'','privacy'=>'A política de privacidade da loja será publicada antes do lançamento.','terms'=>'Os termos de compra serão publicados antes do lançamento.','returns'=>'A política de trocas será publicada antes do lançamento.','pages'=>$pages,'benefits'=>[['title'=>'Entrega para todo o Brasil','description'=>'Frete calculado para o seu CEP.'],['title'=>'Arte autoral','description'=>'Identidade em cada detalhe.'],['title'=>'Atendimento próximo','description'=>'Conte com a nossa equipe.']]],'integrations'=>['melhor_envio_token'=>'','origin_postal_code'=>'','support_email'=>'','sandbox'=>true],'coupons'=>[]];
