<?php
$config=is_file(dirname(__DIR__).'/config.local.php')?require dirname(__DIR__).'/config.local.php':[];
$seed=require dirname(__DIR__).'/seed.php';$settings=$seed['settings'];
try{$db=new PDO('sqlite:'.($config['storage_path']??dirname(__DIR__).'/storage').'/bryxa.sqlite');$raw=$db->query("SELECT data FROM documents WHERE name='settings'")->fetchColumn();if($raw)$settings=json_decode($raw,true);}catch(Throwable $e){}
$route=$_GET['route']??'inicio';$page=$settings['pages'][$route]??null;
$extra=['todos'=>'Todas as peças','contato'=>'Contato','sobre'=>'Nossa essência','trocas'=>'Trocas e devoluções','privacidade'=>'Privacidade','termos'=>'Termos de compra','checkout'=>'Finalizar compra','sacola'=>'Sacola','favoritos'=>'Favoritos','acompanhar'=>'Acompanhar pedido'];
if(!$page&&!isset($extra[$route])){http_response_code(404);$extra[$route]='Página não encontrada';}
$brand=$settings['brand'];$title=($route==='inicio'?($settings['seo_title']??$brand.' · Streetwear inspirado em CS2'):($page['label']??$extra[$route]).' · '.$brand);
$description=$route==='inicio'?($settings['seo_description']??'Streetwear autoral inspirado em Counter-Strike. Conheça os drops BRYXA, moletons, camisetas e peças personalizadas.'):($page['description']??'Conheça a BRYXA e explore nossas peças e informações.');
$domain=preg_replace('/[^a-zA-Z0-9.-]/','',$settings['domain']);$base='https://'.$domain;$url=$base.($route==='inicio'?'/':'/'.$route.'/');$e=fn($s)=>htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');
$private=in_array($route,['checkout','sacola','favoritos','acompanhar']);
$schema=['@context'=>'https://schema.org','@graph'=>[['@type'=>'WebSite','@id'=>$base.'/#website','name'=>$brand,'url'=>$base.'/'],['@type'=>'Organization','name'=>$brand,'url'=>$base.'/'],['@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Início','item'=>$base.'/'],...($route==='inicio'?[]:[['@type'=>'ListItem','position'=>2,'name'=>$page['label']??$extra[$route],'item'=>$url]])]]]];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><base href="/"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=$e($title)?></title><meta name="description" content="<?=$e($description)?>"><meta name="robots" content="<?=$private?'noindex,nofollow':'index,follow'?>"><link rel="canonical" href="<?=$e($url)?>"><meta property="og:type" content="website"><meta property="og:site_name" content="<?=$e($brand)?>"><meta property="og:title" content="<?=$e($title)?>"><meta property="og:description" content="<?=$e($description)?>"><meta property="og:url" content="<?=$e($url)?>"><meta property="og:image" content="<?=$e($base.'/'.($page['banner']??'assets/hero-home-cs2-v4.webp'))?>"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#09090d"><link rel="icon" href="assets/favicon.svg"><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="chat.css"><link rel="stylesheet" href="storefront.css"><script type="application/ld+json"><?=json_encode($schema,JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP)?></script></head><body><div id="app"><main class="container section"><h1><?=$e($title)?></h1><p><?=$e($description)?></p><nav aria-label="Coleções"><?php foreach($settings['pages'] as $slug=>$p)if($p['enabled']):?><a href="<?=$slug==='inicio'?'/':'/'.$e($slug).'/'?>"><?=$e($p['label'])?></a> <?php endif;?></nav></main></div><dialog id="product-dialog"></dialog><div id="toast" role="status"></div><script type="module" src="app.js"></script><script type="module" src="chat.js"></script></body></html>
