<?php
if(!defined('BRYXA_API'))exit;
// Schema upgrades preserve conversations and existing administrator access.
function addColumns(PDO $db,string $table,array $columns):void{$existing=array_column($db->query('PRAGMA table_info('.$table.')')->fetchAll(PDO::FETCH_ASSOC),'name');foreach($columns as $name=>$definition)if(!in_array($name,$existing))$db->exec('ALTER TABLE '.$table.' ADD COLUMN '.$name.' '.$definition);}
addColumns($db,'admins',['display_name'=>"TEXT NOT NULL DEFAULT 'Equipe BRYXA'",'avatar'=>"TEXT NOT NULL DEFAULT ''",'role'=>"TEXT NOT NULL DEFAULT 'owner'",'active'=>'INTEGER NOT NULL DEFAULT 1']);
addColumns($db,'chats',['contact'=>"TEXT NOT NULL DEFAULT '{}'",'store_typing'=>'INTEGER NOT NULL DEFAULT 0','customer_typing'=>'INTEGER NOT NULL DEFAULT 0']);
function adminProfile():array{global $db;$q=$db->prepare('SELECT id,email,display_name,avatar,role,active FROM admins WHERE id=?');$q->execute([$_SESSION['admin_id']??0]);return $q->fetch(PDO::FETCH_ASSOC)?:[];}
function markRead(string $id,string $sender):array{global $db;$db->beginTransaction();$q=$db->prepare('SELECT messages FROM chats WHERE id=?');$q->execute([$id]);$messages=json_decode($q->fetchColumn()?:'[]',true);foreach($messages as &$m)if($m['sender']===$sender&&empty($m['read_at']))$m['read_at']=date('c');unset($m);$q=$db->prepare('UPDATE chats SET messages=? WHERE id=?');$q->execute([json_encode($messages,JSON_UNESCAPED_UNICODE),$id]);$db->commit();return $messages;}
if($method==='POST'&&in_array($action,['chat-send','chat-poll','chat-typing'])){
 $b=body();$token=textValue($b['token']??'',100);$hash=hash('sha256',$token);$q=$db->prepare('SELECT * FROM chats WHERE token_hash=?');$q->execute([$hash]);$thread=$q->fetch(PDO::FETCH_ASSOC);
 if($action==='chat-poll'){if(!$thread)fail('Conversa não encontrada.',404);$messages=markRead($thread['id'],'store');reply(['messages'=>$messages,'contact'=>json_decode($thread['contact'],true),'typing'=>(int)$thread['store_typing']>time()]);}
 if($action==='chat-typing'){if(!$thread)fail('Conversa não encontrada.',404);$q=$db->prepare('UPDATE chats SET customer_typing=? WHERE id=?');$q->execute([!empty($b['typing'])?time()+8:0,$thread['id']]);reply(['ok'=>true]);}
 $message=textValue($b['message']??'',2000);if(!$message)fail('Escreva sua dúvida.');
 $contact=$thread?json_decode($thread['contact'],true):[];
 if(!$thread||empty($contact['email'])){$input=$b['contact']??[];$contact=['name'=>textValue($input['name']??'',100),'email'=>strtolower(textValue($input['email']??'',254)),'whatsapp'=>preg_replace('/\D/','',textValue($input['whatsapp']??'',30))];if(!filter_var($contact['email'],FILTER_VALIDATE_EMAIL)||strlen($contact['whatsapp'])<10||strlen($contact['whatsapp'])>15)fail('Informe seu e-mail e WhatsApp para iniciarmos o atendimento.');if(!$contact['name'])$contact['name']='Visitante';}
 $key=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').':chat');$q=$db->prepare('SELECT count,expires FROM attempts WHERE key=?');$q->execute([$key]);$a=$q->fetch(PDO::FETCH_ASSOC);if($a&&$a['expires']>time()&&$a['count']>=60)fail('Aguarde alguns minutos para enviar outra mensagem.',429);$q=$db->prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END,expires=?');$q->execute([$key,time()+3600,time(),time()+3600]);
 $db->beginTransaction();if(!$thread){$token=bin2hex(random_bytes(32));$hash=hash('sha256',$token);$id=bin2hex(random_bytes(8));$messages=[];}else{$id=$thread['id'];$q=$db->prepare('SELECT messages FROM chats WHERE id=?');$q->execute([$id]);$messages=json_decode($q->fetchColumn(),true);}
 if(count($messages)>=500){$db->rollBack();fail('Esta conversa chegou ao limite de mensagens.');}$messages[]=['sender'=>'customer','text'=>$message,'time'=>date('c')];$q=$db->prepare('INSERT INTO chats(id,token_hash,messages,updated,contact) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET messages=excluded.messages,updated=excluded.updated,contact=excluded.contact,customer_typing=0');$q->execute([$id,$hash,json_encode($messages,JSON_UNESCAPED_UNICODE),date('c'),json_encode($contact,JSON_UNESCAPED_UNICODE)]);$db->commit();reply(['token'=>$token,'messages'=>$messages,'contact'=>$contact]);
}
if($method==='GET'&&$action==='chats'){auth();$rows=$db->query('SELECT id,messages,updated,contact,customer_typing FROM chats ORDER BY updated DESC LIMIT 200')->fetchAll(PDO::FETCH_ASSOC);reply(['chats'=>array_map(fn($r)=>['id'=>$r['id'],'messages'=>json_decode($r['messages'],true),'contact'=>json_decode($r['contact'],true),'updated'=>$r['updated'],'typing'=>(int)$r['customer_typing']>time()],$rows)]);}
if($method==='POST'&&$action==='chat-read'){auth();$id=textValue(body()['id']??'',100);reply(['messages'=>markRead($id,'customer')]);}
if($method==='POST'&&$action==='chat-admin-typing'){auth();$b=body();$q=$db->prepare('UPDATE chats SET store_typing=? WHERE id=?');$q->execute([!empty($b['typing'])?time()+8:0,$b['id']??'']);reply(['ok'=>true]);}
if($method==='POST'&&$action==='chat-reply'){auth();$b=body();$message=textValue($b['message']??'',2000);if(!$message)fail('Escreva sua resposta.');$profile=adminProfile();$db->beginTransaction();$q=$db->prepare('SELECT messages FROM chats WHERE id=?');$q->execute([$b['id']??'']);$raw=$q->fetchColumn();if(!$raw){$db->rollBack();fail('Conversa não encontrada.',404);}$messages=json_decode($raw,true);$messages[]=['sender'=>'store','text'=>$message,'time'=>date('c'),'name'=>$profile['display_name'],'avatar'=>$profile['avatar']];$q=$db->prepare('UPDATE chats SET messages=?,updated=?,store_typing=0 WHERE id=?');$q->execute([json_encode($messages,JSON_UNESCAPED_UNICODE),date('c'),$b['id']]);$db->commit();reply(['ok'=>true]);}
if($method==='GET'&&$action==='staff'){auth(); $profile=adminProfile();reply(['staff'=>$profile['role']!=='owner'?[$profile]:$db->query('SELECT id,email,display_name,avatar,role,active FROM admins')->fetchAll(PDO::FETCH_ASSOC),'profile'=>$profile]);}
if($method==='POST'&&$action==='staff-profile'){auth();$b=body();$name=textValue($b['display_name']??'',100);if(!$name)fail('Informe seu nome de atendimento.');$avatar=!empty($b['avatar'])?safeImage($b['avatar']):'';$q=$db->prepare('UPDATE admins SET display_name=?,avatar=? WHERE id=?');$q->execute([$name,$avatar,$_SESSION['admin_id']]);reply(['ok'=>true]);}
if($method==='POST'&&$action==='staff-create'){auth();if(adminProfile()['role']!=='owner')fail('Somente a proprietária pode criar acessos.',403);$b=body();$role=($b['role']??'support');if(!in_array($role,['support','operations'],true))fail('Permissão inválida.');$email=strtolower(textValue($b['email']??'',254));$name=textValue($b['display_name']??'',100);$password=textValue($b['password']??'',300);$avatar=!empty($b['avatar'])?safeImage($b['avatar']):'';if(!$name||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<12)fail('Informe nome, e-mail e senha de pelo menos 12 caracteres.');$q=$db->prepare('SELECT id FROM admins WHERE email=?');$q->execute([$email]);if($q->fetchColumn())fail('Este e-mail já tem acesso.');$q=$db->prepare('INSERT INTO admins(email,password,display_name,avatar,role) VALUES(?,?,?,?,?)');$q->execute([$email,password_hash($password,PASSWORD_DEFAULT),$name,$avatar,$role]);reply(['ok'=>true]);}

if($method==='POST'&&$action==='staff-access'){auth();if(adminProfile()['role']!=='owner')fail('Somente a proprietária pode gerenciar acessos.',403);$b=body();$id=filter_var($b['id']??0,FILTER_VALIDATE_INT);$role=$b['role']??'support';if(!in_array($role,['support','operations'],true)||!is_bool($b['active']??null))fail('Permissão inválida.');$q=$db->prepare("UPDATE admins SET role=?,active=?,auth_version=auth_version+1 WHERE id=? AND role!='owner'");$q->execute([$role,$b['active']?1:0,$id]);if(!$q->rowCount())fail('Acesso não encontrado.');reply(['ok'=>true]);}
