<?php
if(!defined('BRYXA_API'))exit;
function demoMode():bool{global $config;return !empty($config['demo_mode'])&&PHP_SAPI==='cli-server'&&empty(loadDoc('integrations')['mp_enabled']);}
function demoQuotes():array{return [['id'=>'demo-standard','name'=>'Entrega padrão · SIMULAÇÃO','price'=>19.9,'days'=>7],['id'=>'demo-express','name'=>'Entrega expressa · SIMULAÇÃO','price'=>29.9,'days'=>3]];}
$db->exec('CREATE TABLE IF NOT EXISTS demo_orders (id TEXT PRIMARY KEY,data TEXT NOT NULL,created TEXT NOT NULL,token_hash TEXT NOT NULL); CREATE TABLE IF NOT EXISTS demo_accounts(email TEXT PRIMARY KEY,password TEXT NOT NULL);');
if($method==='GET'&&$action==='demo-config')reply(['enabled'=>demoMode()]);
if(str_starts_with($action,'demo-')&&$action!=='demo-config'&&!demoMode())fail('Modo de teste indisponível.',403);
if($method==='POST'&&$action==='demo-checkout'){
 $b=body();$customer=$b['customer']??[];$clean=[];foreach(['name','email','postal_code','street','number','neighborhood','city','state','complement'] as $key)$clean[$key]=textValue($customer[$key]??'',$key==='email'?254:200);foreach(['name','street','number','neighborhood','city','state'] as $key)if(!$clean[$key])fail('Confira os dados de entrega.');$clean['email']=strtolower($clean['email']);$clean['postal_code']=preg_replace('/\D/','',$clean['postal_code']);if(!filter_var($clean['email'],FILTER_VALIDATE_EMAIL)||strlen($clean['postal_code'])!==8||!preg_match('/^[A-Z]{2}$/',$clean['state']))fail('Confira e-mail, CEP e estado.');
 $items=$b['items']??[];if(!is_array($items)||!count($items)||count($items)>50)fail('Adicione peças à sacola.');$catalog=array_column(loadDoc('products'),null,'id');$lines=[];$cents=0;$counts=[];foreach($items as $item){$p=$catalog[$item['id']??'']??null;$size=textValue($item['size']??'',20);$qty=$item['quantity']??0;if(!$p||!$p['active']||!is_int($qty)||$qty<1||$qty>100)fail('Produto ou quantidade inválida.');$counts[$p['id'].':'.$size]=($counts[$p['id'].':'.$size]??0)+$qty;if(($p['stock'][$size]??0)<$counts[$p['id'].':'.$size])fail('O estoque desta peça mudou. Revise sua sacola.');$cents+=(int)round($p['price']*100)*$qty;$lines[]=['id'=>$p['id'],'name'=>$p['name'],'size'=>$size,'quantity'=>$qty,'price'=>$p['price'],'image'=>$p['image'],'nicks'=>cleanItemNicks($item),'nick'=>cleanItemNick($item),'custom'=>$item['custom']??null];}
 $shipping=null;foreach(demoQuotes() as $q)if($q['id']===($b['shipping_id']??''))$shipping=$q;if(!$shipping)fail('Escolha uma opção de frete.');$discount=0;foreach(loadDoc('coupons') as $coupon)if($coupon['active']&&$coupon['code']===strtoupper((string)($b['coupon']??'')))$discount=(int)round($cents*$coupon['percent']/100);
 $requestKey=textValue($b['request_key']??'',100);if(!preg_match('/^[a-zA-Z0-9-]{16,100}$/',$requestKey))fail('Solicitação inválida.');$id='TESTE-'.strtoupper(substr(hash('sha256',$requestKey),0,10));$q=$db->prepare('SELECT * FROM demo_orders WHERE id=?');$q->execute([$id]);$existing=$q->fetch(PDO::FETCH_ASSOC);if($existing)fail('Este teste já foi aprovado. Veja a confirmação na sua sessão.',409);
 $pricing=cartPricing($items,textValue($b['coupon']??'',40));foreach($lines as &$line)if(!empty($line['custom']))$line['price']=round($line['price']+(loadDoc('settings')['personalization_price']??0),2);unset($line);$token=bin2hex(random_bytes(32));$order=['id'=>$id,'status'=>'Recebido','payment_status'=>'approved_simulated','demo'=>true,'customer'=>$clean,'items'=>$lines,'subtotal'=>$pricing['subtotal'],'discount'=>$pricing['discount'],'gift'=>$pricing['gift'],'shipping'=>$shipping,'total'=>round($pricing['net']+$shipping['price'],2),'method'=>($b['method']??'pix')==='card'?'Cartão (simulado)':'Pix (simulado)','created'=>date('c'),'timeline'=>[['status'=>'Pagamento aprovado (teste)','time'=>date('c'),'source'=>'Simulação']]];$q=$db->prepare('INSERT INTO demo_orders(id,data,created,token_hash) VALUES(?,?,?,?)');$q->execute([$id,json_encode($order,JSON_UNESCAPED_UNICODE),date('c'),hash('sha256',$token)]);orderEmail($order,'payment_approved',$id.':approved','http://127.0.0.1:8080/acompanhar/#'.$token);reply(['order'=>$order,'token'=>$token,'email_preview'=>['to'=>$clean['email'],'subject'=>'[TESTE] Compra confirmada · '.$id,'body'=>'Olá, '.$clean['name'].'. Sua compra de teste '.$id.' foi aprovada automaticamente. Total: R$ '.number_format($order['total'],2,',','.').'. Nenhum valor foi cobrado. Acompanhe pelo link de teste e crie sua senha se desejar.']]);
}
if($method==='POST'&&in_array($action,['demo-track','demo-account'])){
 $b=body();$q=$db->prepare('SELECT data FROM demo_orders WHERE token_hash=?');$q->execute([hash('sha256',textValue($b['token']??'',100))]);$raw=$q->fetchColumn();if(!$raw)fail('Link de acompanhamento inválido.',404);$order=json_decode($raw,true);$email=$order['customer']['email'];$q=$db->prepare('SELECT password FROM demo_accounts WHERE email=?');$q->execute([$email]);$hash=$q->fetchColumn();$authenticated=($_SESSION['demo_customer']??'')===$email;
 if($action==='demo-account'){$password=textValue($b['password']??'',300);if(!$hash){if(strlen($password)<12)fail('Use uma senha com pelo menos 12 caracteres.');$q=$db->prepare('INSERT INTO demo_accounts(email,password) VALUES(?,?)');$q->execute([$email,password_hash($password,PASSWORD_DEFAULT)]);}else{if(!password_verify($password,$hash))fail('Senha incorreta.',401);}session_regenerate_id(true);$_SESSION['demo_customer']=$email;$authenticated=true;}
 if(!$authenticated)reply(['requires_account'=>true,'has_account'=>(bool)$hash,'email'=>$email,'id'=>$order['id']]);reply(['order'=>$order,'requires_account'=>false]);
}
