<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
$configFile=dirname(__DIR__,2).'/config.local.php';
$config=is_file($configFile)?require $configFile:[];
$storage=$config['storage_path']??dirname(__DIR__,2).'/storage';
if(!is_dir($storage))mkdir($storage,0700,true);
session_name('bryxa_admin');
session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','samesite'=>'Strict','path'=>'/']);
session_start();
$_SESSION['csrf']??=bin2hex(random_bytes(32));
function reply(mixed $data,int $status=200): never {http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function fail(string $message,int $status=400): never {reply(['error'=>$message],$status);}
function body():array{$raw=file_get_contents('php://input');$b=json_decode($raw?:'{}',true);if(!is_array($b))fail('Dados inválidos.');return $b;}
function textValue(mixed $v,int $max=200):string{if(!is_string($v))fail('Texto inválido.');if(strlen($v)>$max)fail('Texto muito longo.');return trim($v);}
function auth():void {global $db,$action;if(empty($_SESSION['admin_id']))fail('Entre no painel para continuar.',401);$q=$db->prepare('SELECT role,auth_version,active FROM admins WHERE id=?');$q->execute([$_SESSION['admin_id']]);$row=$q->fetch(PDO::FETCH_ASSOC);$role=$row['role']??null;if($row&&($row['auth_version']??0)!==($_SESSION['admin_auth_version']??0)){unset($_SESSION['admin_id']);fail('Sua senha foi alterada. Entre novamente.',401);}if(!$role||empty($row['active']))fail('Acesso indisponível.',401);if($role==='operations'&&!in_array($action,['admin','staff','staff-profile','password','logout','order-status','order-shipment','order-sync']))fail('Este acesso é exclusivo para pedidos.',403);if($role==='support'&&!in_array($action,['admin','chats','chat-read','chat-reply','chat-admin-typing','staff','staff-profile','upload','password','logout']))fail('Este acesso é exclusivo para atendimento.',403);if(($_SERVER['REQUEST_METHOD']??'GET')!=='GET'&&!hash_equals($_SESSION['csrf'],$_SERVER['HTTP_X_CSRF_TOKEN']??''))fail('Sessão inválida. Atualize a página.',403);}
function safeImage(string $url):string{if(!preg_match('#^(assets|uploads)/[a-zA-Z0-9._-]+\.(webp|png|jpe?g)$#',$url))fail('Imagem inválida. Use o botão Enviar imagem.');return $url;}
define('BRYXA_API',true);require __DIR__.'/secrets.php';
try{
 $db=new PDO('sqlite:'.$storage.'/bryxa.sqlite');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
 $db->exec('CREATE TABLE IF NOT EXISTS documents (name TEXT PRIMARY KEY, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS admins (id INTEGER PRIMARY KEY,email TEXT UNIQUE NOT NULL,password TEXT NOT NULL); CREATE TABLE IF NOT EXISTS subscribers (email TEXT PRIMARY KEY,created TEXT NOT NULL); CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY,data TEXT NOT NULL,created TEXT NOT NULL); CREATE TABLE IF NOT EXISTS attempts (key TEXT PRIMARY KEY,count INTEGER,expires INTEGER);');
 function loadDoc(string $name):array{global $db;$q=$db->prepare('SELECT data FROM documents WHERE name=?');$q->execute([$name]);$data=json_decode($q->fetchColumn()?:'[]',true);if($name==='integrations')foreach(SECRET_FIELDS as $f)if(!empty($data[$f]))$data[$f]=decryptSecret($data[$f]);return $data;}
 function saveDoc(string $name,array $data):void{global $db;if($name==='integrations')foreach(SECRET_FIELDS as $f)if(!empty($data[$f]))$data[$f]=encryptSecret($data[$f]);$q=$db->prepare('INSERT INTO documents(name,data) VALUES(?,?) ON CONFLICT(name) DO UPDATE SET data=excluded.data');$q->execute([$name,json_encode($data,JSON_UNESCAPED_UNICODE)]);}
 if(!loadDoc('settings')){foreach(require dirname(__DIR__,2).'/seed.php' as $k=>$v)saveDoc($k,$v);}
 $legacyRaw=$db->query("SELECT data FROM documents WHERE name='integrations'")->fetchColumn();$legacy=json_decode($legacyRaw?:'[]',true);foreach(SECRET_FIELDS as $field)if(!empty($legacy[$field])&&!str_starts_with($legacy[$field],'enc:v1:')){saveDoc('integrations',loadDoc('integrations'));break;}
 $db->exec('CREATE TABLE IF NOT EXISTS chats (id TEXT PRIMARY KEY,token_hash TEXT NOT NULL,messages TEXT NOT NULL,updated TEXT NOT NULL);');
 $action=$_GET['action']??'store';$method=$_SERVER['REQUEST_METHOD'];
 $adminColumns=array_column($db->query('PRAGMA table_info(admins)')->fetchAll(PDO::FETCH_ASSOC),'name');if(!in_array('active',$adminColumns))$db->exec('ALTER TABLE admins ADD COLUMN active INTEGER NOT NULL DEFAULT 1');$reviewSettings=loadDoc('settings');if(empty($reviewSettings['client_review_v1'])){$reviewSettings['benefits']=array_values(array_filter($reviewSettings['benefits']??[],fn($benefit)=>($benefit['title']??'')!=='Arte autoral'));foreach($reviewSettings['benefits'] as &$benefit)if(($benefit['title']??'')==='Atendimento próximo')$benefit['title']='Atendimento pelo WhatsApp';unset($benefit);$reviewSettings['client_review_v1']=true;saveDoc('settings',$reviewSettings);}require __DIR__.'/shop-options.php';require __DIR__.'/notifications.php';require __DIR__.'/chat.php';require __DIR__.'/demo.php';require __DIR__.'/payments.php';require __DIR__.'/tracking.php';
 if($method==='GET'&&$action==='store'){reply(['settings'=>loadDoc('settings'),'products'=>array_values(array_filter(loadDoc('products'),fn($p)=>$p['active'])),'checkout_enabled'=>demoMode()||mpEnabled(),'demo_mode'=>demoMode()]);}
 if($method==='GET'&&$action==='session'){reply(['authenticated'=>!empty($_SESSION['admin_id']),'csrf'=>$_SESSION['csrf'],'needs_setup'=>(int)$db->query('SELECT COUNT(*) FROM admins')->fetchColumn()===0]);}
 if($method==='POST'&&in_array($action,['setup','login'])){
  $b=body();$email=strtolower(textValue($b['email']??'',254));$password=$b['password']??'';if(!filter_var($email,FILTER_VALIDATE_EMAIL)||!is_string($password))fail('Confira seu e-mail e senha.');
  $key=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').':'.$action);$q=$db->prepare('SELECT count,expires FROM attempts WHERE key=?');$q->execute([$key]);$attempt=$q->fetch(PDO::FETCH_ASSOC);if($attempt&&$attempt['expires']>time()&&$attempt['count']>=8)fail('Muitas tentativas. Aguarde 15 minutos.',429);
  if($action==='setup'){
   if((int)$db->query('SELECT COUNT(*) FROM admins')->fetchColumn()>0)fail('O painel já foi configurado.',409);
   if(empty($config['setup_key'])||!hash_equals($config['setup_key'],(string)($b['setup_key']??'')))fail('Chave de instalação inválida.',403);
   if(strlen($password)<12)fail('Use uma senha com pelo menos 12 caracteres.');
   $q=$db->prepare('INSERT INTO admins(email,password) VALUES(?,?)');$q->execute([$email,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)$db->lastInsertId();
  }else{
   $q=$db->prepare('SELECT * FROM admins WHERE email=?');$q->execute([$email]);$admin=$q->fetch(PDO::FETCH_ASSOC);
   if(!$admin||!password_verify($password,$admin['password'])){$q=$db->prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END,expires=?');$q->execute([$key,time()+900,time(),time()+900]);fail('E-mail ou senha incorretos.',401);}$id=(int)$admin['id'];
  }
  session_regenerate_id(true);$_SESSION['admin_id']=$id;$_SESSION['admin_auth_version']=(int)($admin['auth_version']??0);$_SESSION['csrf']=bin2hex(random_bytes(32));reply(['ok'=>true,'csrf'=>$_SESSION['csrf']]);
 }
 if($method==='POST'&&$action==='logout'){auth();$_SESSION=[];session_destroy();reply(['ok'=>true]);}
 if($method==='POST'&&$action==='password'){auth();$b=body();$q=$db->prepare('SELECT password FROM admins WHERE id=?');$q->execute([$_SESSION['admin_id']]);if(!password_verify($b['current']??'',$q->fetchColumn()))fail('Senha atual incorreta.');if(strlen($b['password']??'')<12)fail('Use pelo menos 12 caracteres.');$q=$db->prepare('UPDATE admins SET password=?,auth_version=auth_version+1 WHERE id=?');$q->execute([password_hash($b['password'],PASSWORD_DEFAULT),$_SESSION['admin_id']]);$_SESSION['admin_auth_version']=($_SESSION['admin_auth_version']??0)+1;reply(['ok'=>true]);}
 if($method==='GET'&&$action==='admin'){auth();$profile=adminProfile();if($profile['role']==='operations'){$orders=array_merge($db->query('SELECT data FROM orders ORDER BY created DESC')->fetchAll(PDO::FETCH_COLUMN),$db->query('SELECT data FROM demo_orders ORDER BY created DESC')->fetchAll(PDO::FETCH_COLUMN));reply(['profile'=>$profile,'settings'=>['brand'=>loadDoc('settings')['brand']],'products'=>[],'orders'=>array_map(fn($o)=>json_decode($o,true),$orders),'integrations'=>[],'coupons'=>[],'subscribers'=>[]]);}if($profile['role']==='support')reply(['profile'=>$profile,'settings'=>['brand'=>loadDoc('settings')['brand']],'products'=>[],'orders'=>[],'integrations'=>[],'coupons'=>[],'subscribers'=>[]]);$integrations=loadDoc('integrations');$integrations['has_token']=!empty($integrations['melhor_envio_token']);$integrations['has_mp_token']=!empty($integrations['mp_access_token']);$integrations['has_mp_webhook']=!empty($integrations['mp_webhook_secret']);foreach(SECRET_FIELDS as $secretField)unset($integrations[$secretField]);$newsletter=$db->query('SELECT email,created FROM subscribers ORDER BY created DESC')->fetchAll(PDO::FETCH_ASSOC);$orders=array_merge($db->query('SELECT data FROM orders ORDER BY created DESC')->fetchAll(PDO::FETCH_COLUMN),$db->query('SELECT data FROM demo_orders ORDER BY created DESC')->fetchAll(PDO::FETCH_COLUMN));reply(['profile'=>$profile,'settings'=>loadDoc('settings'),'products'=>loadDoc('products'),'integrations'=>$integrations,'coupons'=>loadDoc('coupons'),'subscribers'=>$newsletter,'orders'=>array_map(fn($o)=>json_decode($o,true),$orders)]);}
 if($method==='POST'&&$action==='product'){
  auth();$b=body();$b['id']=textValue($b['id']??'p'.bin2hex(random_bytes(6)),50);$b['name']=textValue($b['name']??'',150);if(!$b['name'])fail('Informe o nome do produto.');$b['category']=textValue($b['category']??'',60);$b['collection']=textValue($b['collection']??'',60);if(!isset(loadDoc('settings')['pages'][$b['collection']]))fail('Coleção inválida.');$b['description']=textValue($b['description']??'',5000);$b['image']=safeImage($b['image']??'');$b['active']=(bool)($b['active']??true);$b['featured']=(bool)($b['featured']??false);$b['special_drop']=(bool)($b['special_drop']??false);$b['customizable']=(bool)($b['customizable']??in_array($b['category'],['Moletom','Camiseta','Bermuda'],true));
  foreach(['price','weight','width','height','length'] as $field){if(!is_numeric($b[$field]??null)||(float)$b[$field]<=0)fail('Preço, peso e medidas devem ser maiores que zero.');$b[$field]=round((float)$b[$field],2);}
  $stock=$b['stock']??[];if(!is_array($stock)||count($stock)<1||count($stock)>20)fail('Cadastre pelo menos um tamanho.');$clean=[];foreach($stock as $size=>$qty){$size=textValue((string)$size,20);if(!$size||!is_numeric($qty)||(int)$qty<0||(int)$qty>100000)fail('Estoque inválido.');$clean[$size]=(int)$qty;}$compare=$b['compare_price']??0;if(!is_numeric($compare)||$compare<0||$compare>1000000)fail('Preço anterior inválido.');$b['compare_price']=round((float)$compare,2);if($b['compare_price']>0&&$b['compare_price']<=$b['price'])fail('O preço anterior deve ser maior que o preço atual.');$b['stock']=$clean;$b['sizes']=array_keys($clean);
  $db->beginTransaction();$products=loadDoc('products');$found=false;foreach($products as &$p)if($p['id']===$b['id']){$p=$b;$found=true;}unset($p);if(!$found)$products[]=$b;saveDoc('products',$products);$db->commit();reply(['ok'=>true,'product'=>$b]);
 }
 if($method==='POST'&&$action==='delete-product'){auth();$b=body();$db->beginTransaction();saveDoc('products',array_values(array_filter(loadDoc('products'),fn($p)=>$p['id']!==($b['id']??''))));$db->commit();reply(['ok'=>true]);}
 if($method==='POST'&&$action==='settings'){
  auth();$b=body();$old=loadDoc('settings');foreach(['seo_title','seo_description','brand','domain','announcement','home_products_title','collections_title','newsletter_title','newsletter_description','footer_description','about','contact_email','whatsapp','instagram','discord','privacy','terms','returns'] as $key)if(isset($b[$key]))$old[$key]=textValue($b[$key],10000);
  foreach(['instagram','discord'] as $key)if($old[$key]&&!preg_match('#^https://#',$old[$key]))fail('Links sociais devem começar com https://.');
  foreach(['brand_logo','brand_favicon'] as $key)if(isset($b[$key]))$old[$key]=$b[$key]?safeImage($b[$key]):'';
  foreach(['accent_pink','accent_purple','background_color'] as $key)if(isset($b[$key])){if(!preg_match('/^#[0-9a-fA-F]{6}$/',$b[$key]))fail('Cor inválida.');$old[$key]=$b[$key];}
  if(isset($b['pages'])){if(!is_array($b['pages']))fail('Categorias inválidas.');require_once __DIR__.'/site-settings.php';try{$pages=validateStorePages($b['pages'],loadDoc('products'));}catch(InvalidArgumentException $e){fail($e->getMessage());}foreach($pages as &$page)$page['banner']=safeImage($page['banner']);unset($page);$old['pages']=$pages;}
  if(isset($b['interface_copy'])){if(!is_array($b['interface_copy'])||count($b['interface_copy'])>500)fail('Textos inválidos.');$catalogue=json_decode(file_get_contents(dirname(__DIR__).'/copy-catalogue.json'),true);$copy=[];foreach($b['interface_copy'] as $key=>$value){if(!isset($catalogue[$key]))fail('Texto desconhecido. Atualize o painel.');$text=textValue($value,1000);if($text!=='')$copy[$key]=$text;}$old['interface_copy']=$copy;}
  if(isset($b['sections'])){if(!is_array($b['sections']))fail('Seções inválidas.');$sections=$old['sections']??[];foreach(['hero','featured','benefits','newsletter','social','support'] as $key)if(isset($b['sections'][$key])){if(!is_bool($b['sections'][$key]))fail('Visibilidade inválida.');$sections[$key]=$b['sections'][$key];}$old['sections']=$sections;}
  foreach(['theme_toggle','nick_enabled','recommendation_enabled','hero_buttons'] as $key)if(isset($b[$key])){if(!is_bool($b[$key]))fail('Opção inválida.');$old[$key]=$b[$key];}
  if(isset($b['custom_instructions']))$old['custom_instructions']=textValue($b['custom_instructions'],5000);
  if(isset($b['personalization_price'])){if(!is_numeric($b['personalization_price'])||$b['personalization_price']<0||$b['personalization_price']>10000)fail('Valor de personalização inválido.');$old['personalization_price']=round((float)$b['personalization_price'],2);}
  if(isset($b['gift'])){$g=$b['gift'];if(!is_array($g)||!is_bool($g['enabled']??null))fail('Brinde inválido.');$gift=['enabled'=>$g['enabled'],'name'=>textValue($g['name']??'',150)];foreach(['minimum','weight','width','height','length'] as $key){$max=$key==='minimum'?1000000:1000;if(!is_numeric($g[$key]??null)||$g[$key]<=0||$g[$key]>$max)fail('Confira o valor mínimo, peso e medidas do brinde.');$gift[$key]=round((float)$g[$key],2);}if($gift['enabled']&&!$gift['name'])fail('Informe o nome do brinde.');$old['gift']=$gift;}
  if(isset($b['benefits'])){if(!is_array($b['benefits'])||count($b['benefits'])>6)fail('Benefícios inválidos.');$old['benefits']=array_map(fn($x)=>['title'=>textValue($x['title']??'',100),'description'=>textValue($x['description']??'',250)],$b['benefits']);}saveDoc('settings',$old);reply(['ok'=>true]);
 }
 if($method==='POST'&&$action==='integrations'){auth();$b=body();$i=loadDoc('integrations');if(!empty($b['melhor_envio_token']))$i['melhor_envio_token']=textValue($b['melhor_envio_token'],6000);if(!empty($b['clear_token']))$i['melhor_envio_token']='';$cep=preg_replace('/\D/','',$b['origin_postal_code']??'');if($cep&&!preg_match('/^\d{8}$/',$cep))fail('CEP de origem inválido.');$i['origin_postal_code']=$cep;$i['sandbox']=(bool)($b['sandbox']??true);$email=textValue($b['support_email']??'',254);if($email&&!filter_var($email,FILTER_VALIDATE_EMAIL))fail('E-mail técnico inválido.');$i['support_email']=$email;saveDoc('integrations',$i);reply(['ok'=>true]);}
 if($method==='POST'&&$action==='coupons'){auth();$coupons=body()['coupons']??[];if(!is_array($coupons)||count($coupons)>100)fail('Cupons inválidos.');$clean=[];foreach($coupons as $c){$code=strtoupper(textValue($c['code']??'',40));if(!preg_match('/^[A-Z0-9_-]+$/',$code)||!is_numeric($c['percent']??null)||$c['percent']<1||$c['percent']>100)fail('Código ou desconto inválido.');$clean[]=['code'=>$code,'percent'=>(float)$c['percent'],'active'=>(bool)($c['active']??true)];}saveDoc('coupons',$clean);reply(['ok'=>true]);}
 if($method==='POST'&&$action==='coupon'){$code=strtoupper(textValue(body()['code']??'',40));foreach(loadDoc('coupons') as $c)if($c['active']&&$c['code']===$code)reply(['percent'=>$c['percent']]);fail('Cupom não encontrado ou inativo.');}
 if($method==='POST'&&$action==='subscribe'){ $b=body();$email=strtolower(textValue($b['email']??'',254));if(!filter_var($email,FILTER_VALIDATE_EMAIL)||empty($b['consent']))fail('Informe um e-mail válido e aceite receber novidades.');$q=$db->prepare('INSERT OR IGNORE INTO subscribers(email,created) VALUES(?,?)');$q->execute([$email,date('c')]);reply(['ok'=>true]);}
 if($method==='POST'&&$action==='delete-subscriber'){auth();$q=$db->prepare('DELETE FROM subscribers WHERE email=?');$q->execute([body()['email']??'']);reply(['ok'=>true]);}
 if($method==='POST'&&$action==='upload'){
  auth();$f=$_FILES['file']??null;if(!$f||$f['error']!==UPLOAD_ERR_OK)fail('Não foi possível enviar o arquivo.');if($f['size']>10*1024*1024)fail('Use uma imagem de até 10 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext||!getimagesize($f['tmp_name']))fail('Use JPG, PNG ou WebP.');$dir=dirname(__DIR__).'/uploads';if(!is_dir($dir))mkdir($dir,0755,true);$name=bin2hex(random_bytes(16)).'.'.$ext;if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))fail('Falha ao salvar a imagem.',500);reply(['path'=>'uploads/'.$name]);
 }
 if($method==='GET'&&$action==='media'){auth();$files=[];foreach(['assets','uploads'] as $folder)foreach(glob(dirname(__DIR__).'/'.$folder.'/*')?:[] as $file)if(preg_match('/\.(webp|png|jpg|jpeg)$/i',$file))$files[]=$folder.'/'.basename($file);reply(['files'=>$files]);}
 if($method==='POST'&&$action==='delete-media'){auth();$path=safeImage(body()['path']??'');if(!str_starts_with($path,'uploads/'))fail('Imagens originais do projeto são preservadas.');if(str_contains(json_encode(loadDoc('settings'),JSON_UNESCAPED_SLASHES),$path)||str_contains(json_encode(loadDoc('products'),JSON_UNESCAPED_SLASHES),$path))fail('Esta imagem está em uso. Troque-a no produto ou banner antes de excluir.');$file=dirname(__DIR__).'/'.$path;if(!is_file($file))fail('Imagem não encontrada.',404);unlink($file);reply(['ok'=>true]);}
 if($method==='POST'&&$action==='shipping'){
  $b=body();$cep=preg_replace('/\D/','',$b['postal_code']??'');if(!preg_match('/^\d{8}$/',$cep))fail('Informe um CEP com 8 números.');$cart=$b['items']??[];if(!is_array($cart)||!count($cart)||count($cart)>50)fail('Adicione produtos à sacola.');$products=array_column(loadDoc('products'),null,'id');$items=[];foreach($cart as $item){$p=$products[$item['id']??'']??null;$q=$item['quantity']??0;if(!$p||!$p['active']||!is_int($q)||$q<1||$q>100)fail('Produto ou quantidade inválida.');$items[]=['id'=>$p['id'],'width'=>$p['width'],'height'=>$p['height'],'length'=>$p['length'],'weight'=>$p['weight'],'insurance_value'=>$p['price'],'quantity'=>$q];}
  $pricing=cartPricing($cart,textValue($b['coupon']??'',40));if($pricing['gift'])$items[]=['id'=>'bryxa-gift','width'=>$pricing['gift']['width'],'height'=>$pricing['gift']['height'],'length'=>$pricing['gift']['length'],'weight'=>$pricing['gift']['weight'],'insurance_value'=>0,'quantity'=>1];
  if(demoMode())reply(['quotes'=>demoQuotes(),'demo'=>true,'sandbox'=>false]);$i=loadDoc('integrations');if(!$i['melhor_envio_token']||!$i['origin_postal_code']||!$i['support_email'])fail('A cotação de frete estará disponível quando a loja concluir a configuração.',503);
  $key=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').':shipping');$q=$db->prepare('SELECT count,expires FROM attempts WHERE key=?');$q->execute([$key]);$a=$q->fetch(PDO::FETCH_ASSOC);if($a&&$a['expires']>time()&&$a['count']>=30)fail('Aguarde um minuto para uma nova cotação.',429);$q=$db->prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END,expires=?');$q->execute([$key,time()+60,time(),time()+60]);
  if(!function_exists('curl_init'))fail('O serviço de frete não está disponível.',503);$host=$i['sandbox']?'sandbox.melhorenvio.com.br':'www.melhorenvio.com.br';$ch=curl_init('https://'.$host.'/api/v2/me/shipment/calculate');curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Accept: application/json','Authorization: Bearer '.$i['melhor_envio_token'],'User-Agent: BRYXA ('.$i['support_email'].')'],CURLOPT_POSTFIELDS=>json_encode(['from'=>['postal_code'=>$i['origin_postal_code']],'to'=>['postal_code'=>$cep],'products'=>$items,'options'=>['receipt'=>false,'own_hand'=>false]])]);$result=curl_exec($ch);$status=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);if($status!==200||!$result)fail('Não foi possível consultar o frete. Tente novamente em instantes.',502);$result=json_decode($result,true);if(!is_array($result))fail('O serviço retornou uma resposta inválida.',502);$quotes=[];foreach($result as $s)if(empty($s['error'])&&is_numeric($s['custom_price']??$s['price']??null))$quotes[]=['id'=>$s['id'],'name'=>($s['company']['name']??'').' · '.($s['name']??''),'price'=>(float)($s['custom_price']??$s['price']),'days'=>$s['custom_delivery_time']??$s['delivery_time']??null];if(!$quotes)fail('Nenhuma opção de entrega para este CEP.');$_SESSION['shipping_quote']=['quotes'=>$quotes,'cep'=>$cep,'items'=>json_encode(array_map(fn($x)=>['id'=>$x['id'],'quantity'=>$x['quantity']],$cart)),'pricing'=>hash('sha256',json_encode($pricing)),'coupon'=>strtoupper(trim($b['coupon']??'')),'expires'=>time()+900];reply(['quotes'=>$quotes,'sandbox'=>$i['sandbox']]);
 }
 fail('Operação não encontrada.',404);
}catch(Throwable $e){if(isset($db)&&$db->inTransaction())$db->rollBack();error_log('BRYXA: '.$e->getMessage());fail('Não foi possível concluir. Tente novamente.',500);}
