<?php
if(!defined('BRYXA_API'))exit;
$db->exec('CREATE TABLE IF NOT EXISTS email_outbox(id INTEGER PRIMARY KEY,event_key TEXT UNIQUE,recipient TEXT,template TEXT,subject TEXT,html TEXT,plain TEXT,status TEXT,created TEXT); CREATE TABLE IF NOT EXISTS customer_accounts(email TEXT PRIMARY KEY,password TEXT NOT NULL); CREATE TABLE IF NOT EXISTS password_resets(token_hash TEXT PRIMARY KEY,email TEXT,role TEXT,expires INTEGER);');
foreach(['admins','customer_accounts'] as $table){$columns=array_column($db->query('PRAGMA table_info('.$table.')')->fetchAll(PDO::FETCH_ASSOC),'name');if(!in_array('auth_version',$columns))$db->exec('ALTER TABLE '.$table.' ADD COLUMN auth_version INTEGER NOT NULL DEFAULT 0');}
function emailRender(string $type,array $values):array{$templates=require dirname(__DIR__,2).'/email-templates.php';$t=$templates[$type]??null;if(!$t)throw new RuntimeException('Unknown template');$defaults=['name'=>'Cliente','order_id'=>'BRYXA','total'=>'R$ 0,00','carrier'=>'A confirmar','tracking'=>'A confirmar','update'=>'Consulte o acompanhamento','link'=>'https://'.loadDoc('settings')['domain'].'/acompanhar/'];$v=array_merge($defaults,$values);$replace=[];foreach($v as $k=>$value)$replace['{{'.$k.'}}']=(string)$value;$subject=strtr($t[0],$replace);$heading=strtr($t[1],$replace);$body=strtr($t[2],$replace);$e=fn($s)=>htmlspecialchars($s,ENT_QUOTES,'UTF-8');$html='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"></head><body style="margin:0;background:#f4f3f6;font-family:Arial,sans-serif;color:#25212d"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 12px"><table role="presentation" width="100%" style="max-width:600px;background:#fff;border-radius:12px"><tr><td style="padding:32px"><p style="color:#8e41bd;font-size:28px;font-weight:bold">BRYXA</p><h1 style="font-size:25px">'.$e($heading).'</h1><p style="font-size:16px;line-height:1.7">'.$e($body).'</p><p style="margin:28px 0"><a href="'.$e($v['link']).'" style="display:inline-block;background:#934bcc;color:#fff;padding:15px 22px;border-radius:6px;text-decoration:none">'.$e($t[3]).'</a></p><p style="font-size:12px;color:#777;word-break:break-all">Se o botão não abrir: '.$e($v['link']).'</p><hr style="border:0;border-top:1px solid #eee"><p style="font-size:12px;color:#777">BRYXA · Comunicação sobre sua conta ou pedido. Não responda com senhas ou dados de cartão.</p></td></tr></table></td></tr></table></body></html>';return ['subject'=>$subject,'html'=>$html,'plain'=>$heading."\n\n".$body."\n\n".$v['link']];}
function queueEmail(string $type,string $email,array $values,string $key):void{global $db;if(!filter_var($email,FILTER_VALIDATE_EMAIL))return;$render=emailRender($type,$values);$q=$db->prepare('INSERT OR IGNORE INTO email_outbox(event_key,recipient,template,subject,html,plain,status,created) VALUES(?,?,?,?,?,?,?,?)');$q->execute([$key,$email,$type,$render['subject'],$render['html'],$render['plain'],'Aguardando plataforma de e-mail',date('c')]);}
function orderEmail(array $o,string $type,string $key,string $link=''):void{queueEmail($type,$o['customer']['email'],['name'=>$o['customer']['name'],'order_id'=>$o['id'],'total'=>'R$ '.number_format($o['total'],2,',','.'),'carrier'=>$o['carrier']??'A confirmar','tracking'=>$o['tracking_code']??'A confirmar','update'=>$o['status'],'link'=>$link?:($o['access_link']??'')?:'https://'.loadDoc('settings')['domain'].'/acompanhar/'],$key);}
function saveOrder(array $order,string $table='orders'):void{global $db;$q=$db->prepare('UPDATE '.$table.' SET data=? WHERE id=?');$q->execute([json_encode($order,JSON_UNESCAPED_UNICODE),$order['id']]);}
function stageOrder(array &$o,string $stage,string $source='admin'):void{if(($o['status']??'')===$stage)return;$o['status']=$stage;$o['timeline'][]=['status'=>$stage,'time'=>date('c'),'source'=>$source];$types=['Em produção'=>'production','Enviado'=>'shipped','Em trânsito'=>'in_transit','Entregue'=>'delivered','Concluído'=>'delivered','Cancelado'=>'cancelled'];if(isset($types[$stage]))orderEmail($o,$types[$stage],$o['id'].':stage:'.count($o['timeline']));}
function requestLimit(string $action,int $max=10):void{global $db;$key=hash('sha256',($_SERVER['REMOTE_ADDR']??'local').':'.$action);$q=$db->prepare('SELECT count,expires FROM attempts WHERE key=?');$q->execute([$key]);$r=$q->fetch(PDO::FETCH_ASSOC);if($r&&$r['expires']>time()&&$r['count']>=$max)fail('Aguarde alguns minutos e tente novamente.',429);$q=$db->prepare('INSERT INTO attempts(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires < ? THEN 1 ELSE count+1 END,expires=?');$q->execute([$key,time()+900,time(),time()+900]);}
if($action==='emails'&&$method==='GET'){auth();$templates=require dirname(__DIR__,2).'/email-templates.php';$examples=[];foreach($templates as $type=>$t)$examples[]=['type'=>$type,...emailRender($type,['name'=>'Ana','order_id'=>'BRYXA-EXEMPLO','total'=>'R$ 309,80','tracking'=>'EXEMPLO123BR'])];reply(['templates'=>$examples,'outbox'=>$db->query('SELECT id,recipient,template,subject,status,created FROM email_outbox ORDER BY id DESC LIMIT 200')->fetchAll(PDO::FETCH_ASSOC)]);}
if($action==='email-preview'&&$method==='GET'){auth();$q=$db->prepare('SELECT html FROM email_outbox WHERE id=?');$q->execute([$_GET['id']??0]);reply(['html'=>$q->fetchColumn()?:'']);}
if($action==='forgot-password'&&$method==='POST'){requestLimit('forgot-password',5);$b=body();$email=strtolower(textValue($b['email']??'',254));$role=($b['role']??'')==='admin'?'admin':'customer';$q=$db->prepare('SELECT email FROM '.($role==='admin'?'admins':'customer_accounts').' WHERE email=?');$q->execute([$email]);if($q->fetchColumn()){$token=bin2hex(random_bytes(32));$db->prepare('DELETE FROM password_resets WHERE email=? AND role=?')->execute([$email,$role]);$db->prepare('INSERT INTO password_resets VALUES(?,?,?,?)')->execute([hash('sha256',$token),$email,$role,time()+1800]);queueEmail('password_reset',$email,['link'=>'https://'.loadDoc('settings')['domain'].'/recuperar-senha/#'.$token],hash('sha256',$token));}reply(['message'=>'Se houver uma conta com esse e-mail, o link será preparado para envio.']);}
if($action==='reset-password'&&$method==='POST'){requestLimit('reset-password',10);$b=body();$password=textValue($b['password']??'',300);if(strlen($password)<12)fail('Use pelo menos 12 caracteres.');$hash=hash('sha256',textValue($b['token']??'',100));$db->beginTransaction();$q=$db->prepare('SELECT * FROM password_resets WHERE token_hash=? AND expires>?');$q->execute([$hash,time()]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!$r){$db->rollBack();fail('Link inválido ou expirado. Solicite outro.');}$table=$r['role']==='admin'?'admins':'customer_accounts';$db->prepare('UPDATE '.$table.' SET password=?,auth_version=auth_version+1 WHERE email=?')->execute([password_hash($password,PASSWORD_DEFAULT),$r['email']]);$db->prepare('DELETE FROM password_resets WHERE token_hash=?')->execute([$hash]);$db->commit();queueEmail('password_changed',$r['email'],[],bin2hex(random_bytes(16)));reply(['ok'=>true]);}
